name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
      - v2.0
      - v2.0-deployment
    paths:
      - 'frontend/dotnet-calendar/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/dotnet-calendar/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/dotnet-calendar/package-lock.json

      - name: Install dependencies
        working-directory: frontend/dotnet-calendar
        run: npm ci

      - name: Run tests
        working-directory: frontend/dotnet-calendar
        run: npm test -- --watchAll=false --coverage

      - name: Build application
        working-directory: frontend/dotnet-calendar
        run: npm run build

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend/dotnet-calendar
          vercel-args: '--prod'

      - name: Deploy to Vercel (Preview)
        if: github.ref != 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend/dotnet-calendar